name: Create website

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/create_website.yaml
      - 'docs/**'
      - mkdocs.yml
  schedule:
  - cron: "0 1 * * *" # Run daily, 1 hour after 'update_courses.yaml'
  workflow_run:
    workflows: ["Update courses"]
    types:
      - completed
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install -r requirements.txt natsort

      # Intermediate files needed for ./scripts/create_courses_page.sh,
      # where 'docs/courses_2.md' is created by 'update_courses.yaml'
      - name: Remove intermediate files
        run: |
          rm docs/courses_1.md
          rm docs/courses_2.md

      - name: Deploy website
        run: mkdocs gh-deploy --force
