# Update the courses on a daily basis
on:
  push:
  pull_request:
  schedule:
  - cron: "0 0 2 * *"

name: Update courses

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2

      #- uses: r-lib/actions/setup-pandoc@v2

      #- name: Install libcurl4-openssl-dev
      #  run: sudo apt install -qq libcurl4-openssl-dev
      #  if: matrix.os == 'ubuntu-latest'

      #- name: Install libharfbuzz-dev libfribidi-dev
      #  run: sudo apt install -qq libharfbuzz-dev libfribidi-dev

      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_github("richelbilderbeek/scoreto")
        shell: Rscript {0}

      - name: Create courses
        run: Rscript -e 'scoreto::get_courses_as_markdown()'
